### ISSUE TITLE
Install via HACS installs state-attribute-element files and not state-element files

### ISSUE THREAD

**Issue by Albertjvanr** [custom-cards/state-element#2]
**Version of the cusom_component**
0.0.1

**Describe the bug**
Install via HACS installs state-attribute-element files and not state-element files. Manual download of the custom component files and replacing the files downloaded by HACS fixes the issue, which means that it is downloading the state-attribute-element files. The js file has the wrong custom card name in the code

**log**

```
Logs are not applicable, I think. The HACS component is downloading the wrong js file
```

**Comment by ludeeus** [comment]
Still, paste logs (with debug active for `hacs`)

**Comment by Albertjvanr** [comment]
Hi,

Thank you for the assistance.  I’m very new to github and don’t have any experience in HASSIO on debug. Any chance you can tell me how to do this so I can paste the logs?

Would really like to contribute.

Much appreciated.

Albert

**Comment by ludeeus** [comment]
oh.. I thought this issue was filed in the HACS repo.
Since this is not an issue with this repo, but with HACS, you should open an issue in the HACS repo for this issue. 

https://github.com/custom-components/hacs/issues/new?template=issue.md

The template there tells you what to include and how to do it :)
